"""empty message

Revision ID: 8a36bb65e4f1
Revises: 
Create Date: 2018-10-20 10:23:23.470221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a36bb65e4f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('b_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_title', sa.String(length=128), nullable=True),
    sa.Column('b_content', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('b_id')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_name', sa.String(length=64), nullable=True),
    sa.Column('u_email', sa.String(length=128), nullable=True),
    sa.Column('u_password', sa.String(length=64), nullable=True),
    sa.Column('u_icon', sa.Integer(), nullable=True),
    sa.Column('u_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('u_name')
    )
    op.create_table('collection',
    sa.Column('c_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_u_id', sa.Integer(), nullable=True),
    sa.Column('c_b_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_b_id'], ['blog.b_id'], ),
    sa.ForeignKeyConstraint(['c_u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('c_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    op.drop_table('user')
    op.drop_table('blog')
    # ### end Alembic commands ###
